<a href="https://colab.research.google.com/github/ckh0103/data_anal/blob/main/ch04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gdown
gdown.download("https://bit.ly/3736JW1", 'ns_book6.csv', quiet=False)

Downloading...
From: https://bit.ly/3736JW1
To: /content/ns_book6.csv
100%|██████████| 55.0M/55.0M [00:02<00:00, 26.7MB/s]

'ns_book6.csv'

In [5]:
# 통계처리의 정확성을 위해서 잘못된 데이터의 보정과 필요없는 데이터 제거 선처리 해야만 한다.

import pandas as pd
ns_book6 = pd.read_csv('ns_book6.csv', low_memory=False)
ns_book6.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021.0,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021.0,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021.0,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021.0,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021.0,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19

In [3]:
# 데이터프레임의 데이터들에 대해 정리해서 서술해 준다.

ns_book6.describe()

                  번호           발행년도           도서권수           대출건수
count  379976.000000  379976.000000  379976.000000  379976.000000
mean   201726.332847    2008.516306       1.135874      11.504629
std    115836.454596       8.780529       0.483343      19.241926
min         1.000000    1947.000000       0.000000       0.000000
25%    102202.750000    2003.000000       1.000000       2.000000
50%    203179.500000    2009.000000       1.000000       6.000000
75%    301630.250000    2015.000000       1.000000      14.000000
max    401681.000000    2650.000000      40.000000    1765.000000

In [4]:
sum(ns_book6['도서권수'] == 0)

3206

In [7]:
# 도서권수가 0이 아닌 데이터만 처리
ns_book7 = ns_book6[ns_book6['도서권수'] != 0]

In [11]:
ns_book7.describe(percentiles=[0.3, 0.6, 0.9])

                  번호           발행년도           도서권수           대출건수
count  376770.000000  376770.000000  376770.000000  376770.000000
mean   202977.476649    2008.460076       1.145540      11.593439
std    115298.245784       8.773148       0.473853      19.279409
min         1.000000    1947.000000       1.000000       0.000000
30%    124649.700000    2004.000000       1.000000       2.000000
50%    204550.500000    2009.000000       1.000000       6.000000
60%    243537.400000    2011.000000       1.000000       8.000000
90%    361341.100000    2018.000000       2.000000      28.000000
max    401681.000000    2650.000000      40.000000    1765.000000

In [13]:
# object - 실제적인 데이터
# freq : 빈도수
ns_book7.describe(include='object')

,도서명,저자,출판사,ISBN,세트 ISBN,부가기호,권,주제분류번호,등록일자
count,376770,376770,376770,376770,55866,308252,61793,359792,376770
unique,336408,248850,21875,350810,14875,17,834,12467,4562
top,승정원일기,세종대왕기념사업회 [편],문학동네,9788937430299,9788937460005,0,1,813.6,1970-01-01
freq,250,303,4410,206,702,158235,13282,14816,28185

In [16]:
# 평균 구하기

# x1, x2, x3
x = [10, 20, 30]

sum = 0

for i in range(3):
  sum += x[i]

print("평균", sum / len(x))
print(f"합계 {sum}")

평균 20.0
합계 60

In [18]:
ns_book7.describe()

                  번호           발행년도           도서권수           대출건수
count  376770.000000  376770.000000  376770.000000  376770.000000
mean   202977.476649    2008.460076       1.145540      11.593439
std    115298.245784       8.773148       0.473853      19.279409
min         1.000000    1947.000000       1.000000       0.000000
25%    104488.250000    2003.000000       1.000000       2.000000
50%    204550.500000    2009.000000       1.000000       6.000000
75%    302346.750000    2015.000000       1.000000      14.000000
max    401681.000000    2650.000000      40.000000    1765.000000

In [17]:
# 평균 구하기

ns_book7['대출건수'].mean()

np.float64(11.593438968070707)

In [19]:
# 중앙값 구하기

ns_book7['대출건수'].median()

6.0

In [21]:
# 데이터의 개수가 홀수면 중앙의 값이 한개로 정해진다.
# 데이터의 개수가 짝수면 중앙에 위치한 2개의 숫자를 더해서 평균을 내준다.
temp_df = pd.DataFrame([1, 2, 5, 10])
temp_df.median()

0    3.5
dtype: float64

In [22]:
# 중복된 값을 제거하고 중앙값 구하기

ns_book7['대출건수'].drop_duplicates().median()

183.0

In [26]:
print(ns_book7['대출건수'].min())
print(ns_book7['대출건수'].max())

0
1765

In [27]:
# 분위수 구하기 : 0(0%) ~ 1(100%)
# quantile() -> 괄호 안 아무것도 안쓸 시에는 50% 의 데이터를 구한다.
ns_book7['대출건수'].quantile(0.25)

np.float64(2.0)

In [28]:
ns_book7['대출건수'].quantile([0.25, 0.5, 0.75])

0.25     2.0
0.50     6.0
0.75    14.0
Name: 대출건수, dtype: float64

In [32]:
# 분산 구하기 - 평균에서 떨어진 정도의 숫자
# 10 * 10 -> 분산 / 10 -> 표준편차

#ns_book7['대출건수'].var()
print(ns_book7['대출건수'].mean())
print(ns_book7['대출건수'].std())

11.593438968070707
19.27940949382766

In [35]:
# 최빈값 - 최대로 많이 나타나는 값

ns_book7['대출건수'].mode()
#ns_book7['도서명'].mode()
#ns_book7['발행년도'].mode()

0    0
Name: 대출건수, dtype: int64

In [36]:
ns_book7.mean(numeric_only=True)

번호      202977.476649
발행년도      2008.460076
도서권수         1.145540
대출건수        11.593439
dtype: float64

In [38]:
# 최빈수에 해당되는 데이터 가져오기
ns_book7.loc[:,'도서명':].mode()

,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,승정원일기,세종대왕기념사업회 [편],문학동네,2012.0,9788937430299,9788937460005,0,1,813.6,1,0,1970-01-01

In [ ]:
ns_book7.to_csv('ns_book7.csv', index=False)